# Generated by Django 5.2.4 on 2025-07-18 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scholarships", "0002_scholarship_created_by_scholarship_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sponsoredstudent",
            managers=[],
        ),
    ]
