# Generated by Django 5.2.4 on 2025-07-30 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0005_alter_major_program_type"),
        ("people", "0009_alter_studentphoto_managers_and_more"),
        ("scholarships", "0003_alter_sponsoredstudent_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic cycle this scholarship applies to (Language, BA, or MA). Students must re-enter scholarships when transitioning between cycles.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scholarships",
                to="curriculum.cycle",
                verbose_name="Academic Cycle",
            ),
        ),
        migrations.AddIndex(
            model_name="scholarship",
            index=models.Index(fields=["student", "cycle", "status"], name="scholarship_student_ef4b5b_idx"),
        ),
        migrations.AddIndex(
            model_name="scholarship",
            index=models.Index(fields=["cycle", "status"], name="scholarship_cycle_i_8050da_idx"),
        ),
        migrations.AddConstraint(
            model_name="scholarship",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["APPROVED", "ACTIVE"]), ("cycle__isnull", False)),
                fields=("student", "cycle", "scholarship_type", "start_date"),
                name="unique_scholarship_per_student_cycle_type_date",
            ),
        ),
    ]
