# Generated by Django 5.2.4 on 2025-08-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholarships", "0006_add_ngo_payment_mode_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="scholarship_type",
            field=models.CharField(
                choices=[
                    ("MERIT", "Merit-Based"),
                    ("NEED", "Need-Based"),
                    ("SPONSORED", "Sponsor-Funded"),
                    ("EMERGENCY", "Emergency Aid"),
                    ("STAFF", "Staff Scholarship"),
                    ("ACADEMIC", "Academic Excellence"),
                ],
                help_text="Type of scholarship",
                max_length=20,
                verbose_name="Scholarship Type",
            ),
        ),
    ]
