# Generated by Django 5.2 on 2025-01-18

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add visibility field to StudentActivityLog model to control who can view audit log entries.

    This migration enhances the StudentActivityLog model by adding a visibility field that
    determines whether log entries are visible only to staff, to students, or publicly.
    The default is STAFF_ONLY to maintain backward compatibility and security.
    """

    dependencies = [
        ("common", "0002_alter_room_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentactivitylog",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("STAFF_ONLY", "Staff Only"),
                    ("STUDENT_VISIBLE", "Student Can View"),
                    ("PUBLIC", "Public Record"),
                ],
                default="STAFF_ONLY",
                help_text="Who can view this audit log entry",
                max_length=20,
                verbose_name="Visibility",
            ),
        ),
        # Add index for visibility field to support efficient filtering
        migrations.AddIndex(
            model_name="studentactivitylog",
            index=models.Index(
                fields=["visibility", "-created_at"],
                name="common_stud_visibil_8f4d3c_idx",
            ),
        ),
    ]
