# Generated by Django 5.2.4 on 2025-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0006_alter_studentcourseoverride_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalrequirementfulfillment",
            name="completion_status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("ON_HOLD", "On Hold"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                default="COMPLETED",
                help_text="Status of this individual requirement fulfillment",
                max_length=20,
                verbose_name="Completion Status",
            ),
        ),
        migrations.AddField(
            model_name="canonicalrequirementfulfillment",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this fulfillment was last modified", verbose_name="Last Updated"
            ),
        ),
    ]
