# Generated by Django 5.2.4 on 2025-08-05 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0008_drop_old_studentdegreeprogress_rename_fulfillment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentdegreeprogress",
            options={
                "ordering": ["student", "canonical_requirement__sequence_number"],
                "verbose_name": "Student Degree Progress",
                "verbose_name_plural": "Student Degree Progress",
            },
        ),
        migrations.RenameIndex(
            model_name="studentdegreeprogress",
            new_name="academic_st_student_ad1d66_idx",
            old_name="academic_ca_student_0c4a54_idx",
        ),
        migrations.RenameIndex(
            model_name="studentdegreeprogress",
            new_name="academic_st_canonic_8a2fb1_idx",
            old_name="academic_ca_canonic_167ca6_idx",
        ),
        migrations.RenameIndex(
            model_name="studentdegreeprogress",
            new_name="academic_st_fulfill_e1338c_idx",
            old_name="academic_ca_fulfill_e82546_idx",
        ),
        migrations.RenameIndex(
            model_name="studentdegreeprogress",
            new_name="academic_st_fulfill_936c77_idx",
            old_name="academic_ca_fulfill_21afd5_idx",
        ),
    ]
