# Generated by Django 5.2.4 on 2025-08-03 01:32

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0009_remove_seniorprojectgroup_graduation_date_and_more"),
        ("enrollment", "0022_add_student_cycle_status"),
        ("people", "0009_alter_studentphoto_managers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programtransition",
            options={
                "ordering": ["from_enrollment__student", "transition_date"],
                "verbose_name": "Program Transition",
                "verbose_name_plural": "Program Transitions",
            },
        ),
        migrations.AlterModelManagers(
            name="programperiod",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="studentcyclestatus",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="academicjourney",
            name="unique_journey_period",
        ),
        migrations.RemoveIndex(
            model_name="academicjourney",
            name="enrollment__journey_636400_idx",
        ),
        migrations.RemoveIndex(
            model_name="academicjourney",
            name="enrollment__current_d9c1f7_idx",
        ),
        migrations.RemoveIndex(
            model_name="programtransition",
            name="enrollment__journey_9e8a14_idx",
        ),
        migrations.RemoveIndex(
            model_name="programtransition",
            name="enrollment__transit_4c6f8f_idx",
        ),
        migrations.RemoveIndex(
            model_name="programtransition",
            name="enrollment__complet_d5c2e9_idx",
        ),
        migrations.RenameIndex(
            model_name="programperiod",
            new_name="enrollment__journey_fb1991_idx",
            old_name="enrollment__journey_9f8b14_idx",
        ),
        migrations.RenameIndex(
            model_name="programperiod",
            new_name="enrollment__transit_495ebb_idx",
            old_name="enrollment__transit_5c6f9f_idx",
        ),
        migrations.RenameIndex(
            model_name="programperiod",
            new_name="enrollment__complet_28c73f_idx",
            old_name="enrollment__complet_d6c3e9_idx",
        ),
        migrations.AlterUniqueTogether(
            name="programtransition",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="academicjourney",
            name="accumulated_credits",
        ),
        migrations.RemoveField(
            model_name="academicjourney",
            name="courses_completed",
        ),
        migrations.RemoveField(
            model_name="academicjourney",
            name="language_level",
        ),
        migrations.AddField(
            model_name="programtransition",
            name="credits_transferred",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Credits Transferred"),
        ),
        migrations.AddField(
            model_name="programtransition",
            name="gap_days",
            field=models.PositiveIntegerField(default=0, help_text="Days between programs", verbose_name="Gap Days"),
        ),
        migrations.AddField(
            model_name="programtransition",
            name="transition_reason",
            field=models.TextField(blank=True, verbose_name="Transition Reason"),
        ),
        migrations.AddField(
            model_name="programtransition",
            name="transition_term",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="curriculum.term"
            ),
        ),
        migrations.AddField(
            model_name="studentcyclestatus",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AddField(
            model_name="studentcyclestatus",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Indicates if this record has been soft deleted", verbose_name="Is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="academicjourney",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific program or major for this period",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journey_periods",
                to="curriculum.major",
                verbose_name="Program/Major",
            ),
        ),
        migrations.AlterField(
            model_name="academicjourney",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("LANGUAGE", "Language Program"),
                    ("BA", "Bachelor's Degree"),
                    ("MA", "Master's Degree"),
                    ("PHD", "Doctoral Degree"),
                    ("CERT", "Certificate Program"),
                ],
                db_index=True,
                help_text="Type of program for this period",
                max_length=20,
                verbose_name="Program Type",
            ),
        ),
        migrations.AlterField(
            model_name="academicjourney",
            name="start_date",
            field=models.DateField(
                db_index=True, help_text="Date when this program period started", verbose_name="Start Date"
            ),
        ),
        migrations.AlterField(
            model_name="academicjourney",
            name="start_term",
            field=models.ForeignKey(
                help_text="Term when this program period started",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journey_starts",
                to="curriculum.term",
                verbose_name="Start Term",
            ),
        ),
        migrations.AlterField(
            model_name="academicjourney",
            name="student",
            field=models.ForeignKey(
                help_text="Student whose program period is being tracked",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_journeys",
                to="people.studentprofile",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="academicjourney",
            name="term_code",
            field=models.CharField(
                help_text="Term code when the change took place", max_length=20, verbose_name="Term Code"
            ),
        ),
        migrations.AlterField(
            model_name="programperiod",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time when the record was created", verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="programperiod",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="programperiod",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AlterField(
            model_name="programperiod",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Indicates if this record has been soft deleted", verbose_name="Is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="programperiod",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date and time when the record was last updated", verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="programperiod",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="programtransition",
            name="transition_date",
            field=models.DateField(db_index=True, verbose_name="Transition Date"),
        ),
        migrations.AlterField(
            model_name="programtransition",
            name="transition_type",
            field=models.CharField(
                choices=[
                    ("PROG", "Natural Progression (e.g., IEAP to BA)"),
                    ("MAJOR", "Change of Major"),
                    ("LEVEL", "Level Change (e.g., BA to MA)"),
                    ("LAT", "Lateral Move (e.g., between language programs)"),
                    ("RESTART", "Program Restart"),
                ],
                max_length=10,
                verbose_name="Transition Type",
            ),
        ),
        migrations.AddIndex(
            model_name="academicjourney",
            index=models.Index(fields=["student", "start_date"], name="enrollment__student_f8fdeb_idx"),
        ),
        migrations.AddIndex(
            model_name="academicjourney",
            index=models.Index(fields=["transition_status", "program_type"], name="enrollment__transit_0b0c79_idx"),
        ),
        migrations.AddIndex(
            model_name="academicjourney",
            index=models.Index(fields=["program", "transition_status"], name="enrollment__program_d85365_idx"),
        ),
        migrations.AddIndex(
            model_name="programtransition",
            index=models.Index(fields=["transition_date"], name="transition_date_idx"),
        ),
        migrations.AddIndex(
            model_name="programtransition",
            index=models.Index(fields=["transition_type"], name="transition_type_idx"),
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="completed_credits",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="completion_status",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="confidence_score",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="duration_months",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="from_program_type",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="gpa",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="journey",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="language_level",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="program_name",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="sequence_number",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="term_count",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="to_program",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="to_program_type",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="total_credits",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="programtransition",
            name="updated_by",
        ),
    ]
