# Generated by Django 5.2.5 on 2025-08-28 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorprojectgroup',
            name='advisor',
            field=models.ForeignKey(help_text='Faculty member supervising this project', on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_advised_senior_projects', to='people.teacherprofile', verbose_name='Faculty Advisor'),
        ),
        migrations.AddField(
            model_name='seniorprojectgroup',
            name='course',
            field=models.ForeignKey(help_text='Course this senior project is associated with', limit_choices_to={'is_senior_project': True}, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_senior_project_groups', to='curriculum.course', verbose_name='Senior Project Course'),
        ),
        migrations.AddField(
            model_name='seniorprojectgroup',
            name='students',
            field=models.ManyToManyField(help_text='Students participating in this senior project (1-5 students)', related_name='curriculum_senior_project_groups', to='people.studentprofile', verbose_name='Group Members'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['term_type', '-start_date'], name='curriculum__term_ty_50f1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['is_active', '-start_date'], name='curriculum__is_acti_055b77_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['ba_cohort_number'], name='curriculum__ba_coho_b6be60_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['ma_cohort_number'], name='curriculum__ma_coho_e06c91_idx'),
        ),
        migrations.AddField(
            model_name='seniorprojectgroup',
            name='term',
            field=models.ForeignKey(help_text='Term when this project is being conducted', on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_senior_project_groups', to='curriculum.term', verbose_name='Term'),
        ),
        migrations.AddIndex(
            model_name='textbook',
            index=models.Index(fields=['title'], name='curriculum__title_238af0_idx'),
        ),
        migrations.AddIndex(
            model_name='textbook',
            index=models.Index(fields=['author'], name='curriculum__author_44a3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='textbook',
            index=models.Index(fields=['isbn'], name='curriculum__isbn_d2dabe_idx'),
        ),
        migrations.AddField(
            model_name='courseparttemplate',
            name='textbooks',
            field=models.ManyToManyField(blank=True, help_text='Required textbooks for this part (curriculum decision)', related_name='part_templates', to='curriculum.textbook', verbose_name='Textbooks'),
        ),
        migrations.AddIndex(
            model_name='courseprerequisite',
            index=models.Index(fields=['course', 'is_active'], name='curriculum__course__4610c4_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprerequisite',
            index=models.Index(fields=['prerequisite', 'is_active'], name='curriculum__prerequ_c7d0f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseprerequisite',
            unique_together={('prerequisite', 'course')},
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['division', 'is_active'], name='curriculum__divisio_4f85a2_idx'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['display_order'], name='curriculum__display_d4b97a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('division', 'short_name')},
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['cycle', 'is_active'], name='curriculum__cycle_i_630962_idx'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['code'], name='curriculum__code_584e08_idx'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['program_type', 'is_active'], name='curriculum__program_495f50_idx'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['faculty_code'], name='curriculum__faculty_9dd5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['degree_awarded'], name='curriculum__degree__7f9523_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='major',
            unique_together={('cycle', 'code')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='curriculum__code_98f532_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['cycle', 'is_active'], name='curriculum__cycle_i_74c43d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_foundation_year'], name='curriculum__is_foun_8eba99_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_senior_project'], name='curriculum__is_seni_ae0e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='seniorprojectgroup',
            index=models.Index(fields=['course', 'term'], name='curriculum__course__6d1387_idx'),
        ),
        migrations.AddIndex(
            model_name='seniorprojectgroup',
            index=models.Index(fields=['status'], name='curriculum__status_3d13c5_idx'),
        ),
        migrations.AddIndex(
            model_name='seniorprojectgroup',
            index=models.Index(fields=['advisor'], name='curriculum__advisor_ec3329_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seniorprojectgroup',
            unique_together={('course', 'term', 'project_title')},
        ),
        migrations.AddIndex(
            model_name='courseparttemplate',
            index=models.Index(fields=['course', 'is_active'], name='curriculum__course__e954dc_idx'),
        ),
        migrations.AddIndex(
            model_name='courseparttemplate',
            index=models.Index(fields=['course', 'session_number'], name='curriculum__course__c6aaac_idx'),
        ),
        migrations.AddIndex(
            model_name='courseparttemplate',
            index=models.Index(fields=['part_type'], name='curriculum__part_ty_dd9a46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseparttemplate',
            unique_together={('course', 'part_code')},
        ),
    ]
