# Generated by Django 5.2.4 on 2025-07-30 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0005_alter_major_program_type"),
        ("scheduling", "0003_classheader_combined_class_group"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classheader",
            unique_together={("course", "term", "section_id", "time_of_day")},
        ),
    ]
