# Generated by Django 5.2.5 on 2025-08-17 05:26

from django.db import migrations, models
from uuid_extensions import uuid7


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0006_add_class_part_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classpart",
            name="class_part_type",
            field=models.CharField(
                choices=[
                    ("MAIN", "Main Class"),
                    ("LECTURE", "Lecture"),
                    ("DISCUSSION", "Discussion"),
                    ("LAB", "Laboratory"),
                    ("COMPUTER", "Computer Lab"),
                    ("WORKSHOP", "Workshop"),
                    ("TUTORIAL", "Tutorial"),
                    ("PROJECT", "Project"),
                    ("GRAMMAR", "Grammar"),
                    ("CONVERSATION", "Conversation"),
                    ("WRITING", "Writing"),
                    ("READING", "Reading"),
                    ("LISTENING", "Listening"),
                    ("SPEAKING", "Speaking"),
                    ("VENTURES", "Ventures"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="MAIN",
                help_text="Type of class component",
                max_length=15,
                verbose_name="Class Part Type",
            ),
        ),
        migrations.AlterField(
            model_name="classpart",
            name="internal_part_id",
            field=models.UUIDField(
                default=uuid7, editable=False, help_text="Immutable internal identifier for this part", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="classparttemplate",
            name="class_part_type",
            field=models.CharField(
                choices=[
                    ("MAIN", "Main Class"),
                    ("LECTURE", "Lecture"),
                    ("DISCUSSION", "Discussion"),
                    ("LAB", "Laboratory"),
                    ("COMPUTER", "Computer Lab"),
                    ("WORKSHOP", "Workshop"),
                    ("TUTORIAL", "Tutorial"),
                    ("PROJECT", "Project"),
                    ("GRAMMAR", "Grammar"),
                    ("CONVERSATION", "Conversation"),
                    ("WRITING", "Writing"),
                    ("READING", "Reading"),
                    ("LISTENING", "Listening"),
                    ("SPEAKING", "Speaking"),
                    ("VENTURES", "Ventures"),
                    ("OTHER", "Other"),
                ],
                default="MAIN",
                help_text="Type of class component",
                max_length=20,
                verbose_name="Class Part Type",
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="internal_session_id",
            field=models.UUIDField(
                default=uuid7, editable=False, help_text="Immutable internal identifier for this session", unique=True
            ),
        ),
    ]
