# Generated by Django 5.2.5 on 2025-08-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0012_alter_classpart_class_part_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classpart",
            name="class_part_code",
            field=models.IntegerField(
                help_text="Numeric code for ordering multiple parts within a class session (1, 2, 3, etc.)",
                verbose_name="Class Part Code",
            ),
        ),
    ]
