# Generated by Django 5.2.4 on 2025-07-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0002_add_combined_course_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="classheader",
            name="combined_class_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group this class belongs to (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_class_headers",
                to="scheduling.combinedclassgroup",
                verbose_name="Combined Class Group",
            ),
        ),
    ]
