# Generated by Django 5.2.4 on 2025-08-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0004_alter_classheader_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="classpart",
            name="template_derived",
            field=models.BooleanField(
                default=False,
                help_text="Whether this class part was derived from a curriculum template",
                verbose_name="Template Derived",
            ),
        ),
    ]
