# Generated by Django 5.2.5 on 2025-08-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0008_convert_class_part_code_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classpart",
            name="class_part_code",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Numeric identifier for this part (1, 2, 3, etc.)", verbose_name="Class Part Code"
            ),
        ),
        migrations.AlterField(
            model_name="classparttemplate",
            name="class_part_code",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Numeric identifier for this part (1, 2, 3, etc.)", verbose_name="Class Part Code"
            ),
        ),
    ]
