# Generated by Django 5.2.5 on 2025-08-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0010_add_ba_class_part_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classpart",
            name="class_part_type",
            field=models.CharField(
                choices=[
                    ("MAIN", "Main Class"),
                    ("LECTURE", "Lecture"),
                    ("DISCUSSION", "Discussion"),
                    ("LAB", "Laboratory"),
                    ("COMPUTER", "Computer Lab"),
                    ("WORKSHOP", "Workshop"),
                    ("TUTORIAL", "Tutorial"),
                    ("PROJECT", "Project"),
                    ("GRAMMAR", "Grammar"),
                    ("CONVERSATION", "Conversation"),
                    ("WRITING", "Writing"),
                    ("READING", "Reading"),
                    ("LISTENING", "Listening"),
                    ("SPEAKING", "Speaking"),
                    ("VENTURES", "Ventures"),
                    ("BA", "Bachelor's Degree"),
                    ("MA", "Master's Degree"),
                    ("PRACTICUM", "Practicum"),
                    ("EXCHANGE", "Exchange Program"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="MAIN",
                help_text="Type of class component",
                max_length=15,
                verbose_name="Class Part Type",
            ),
        ),
        migrations.AlterField(
            model_name="classparttemplate",
            name="class_part_type",
            field=models.CharField(
                choices=[
                    ("MAIN", "Main Class"),
                    ("LECTURE", "Lecture"),
                    ("DISCUSSION", "Discussion"),
                    ("LAB", "Laboratory"),
                    ("COMPUTER", "Computer Lab"),
                    ("WORKSHOP", "Workshop"),
                    ("TUTORIAL", "Tutorial"),
                    ("PROJECT", "Project"),
                    ("GRAMMAR", "Grammar"),
                    ("CONVERSATION", "Conversation"),
                    ("WRITING", "Writing"),
                    ("READING", "Reading"),
                    ("LISTENING", "Listening"),
                    ("SPEAKING", "Speaking"),
                    ("VENTURES", "Ventures"),
                    ("BA", "Bachelor's Degree"),
                    ("MA", "Master's Degree"),
                    ("PRACTICUM", "Practicum"),
                    ("EXCHANGE", "Exchange Program"),
                    ("OTHER", "Other"),
                ],
                default="MAIN",
                help_text="Type of class component",
                max_length=20,
                verbose_name="Class Part Type",
            ),
        ),
    ]
