# Generated by Django 5.2.5 on 2025-08-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0013_change_class_part_code_to_integer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classpart",
            name="class_part_code",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Numeric identifier for this part (1, 2, 3, etc.)", verbose_name="Class Part Code"
            ),
        ),
    ]
