# Generated by Django 5.2.x

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholarships", "0005_update_athletic_to_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("DIRECT", "Direct Payment - Student pays with NGO funds"),
                    ("BULK_INVOICE", "Bulk Invoice - NGO pays directly"),
                ],
                default="DIRECT",
                help_text="How sponsored students pay for their tuition",
                max_length=20,
                verbose_name="Payment Mode",
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("TERM", "Per Academic Term"),
                    ("QUARTERLY", "Quarterly"),
                    ("YEARLY", "Yearly"),
                ],
                default="TERM",
                help_text="Frequency of bulk invoice generation (only for BULK_INVOICE mode)",
                max_length=20,
                verbose_name="Billing Cycle",
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="invoice_generation_day",
            field=models.IntegerField(
                blank=True,
                help_text="Day of month/term to generate bulk invoices (1-28)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)],
                verbose_name="Invoice Generation Day",
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="payment_terms_days",
            field=models.IntegerField(
                default=30,
                help_text="Number of days for payment after invoice generation",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)],
                verbose_name="Payment Terms (Days)",
            ),
        ),
    ]
