# Generated by Django 5.2.4 on 2025-07-24 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0004_alter_course_code"),
        ("finance", "0004_alter_financialtransaction_transaction_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coursepricing",
            name="unique_default_per_course_tier",
        ),
        migrations.AlterUniqueTogether(
            name="coursepricing",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="coursepricing",
            name="pricing_tier",
            field=models.ForeignKey(
                blank=True,
                help_text="Pricing tier this rate applies to (leave blank for course-specific pricing)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_pricing",
                to="finance.pricingtier",
                verbose_name="Pricing Tier",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepricing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True), ("pricing_tier__isnull", False)),
                fields=("course", "pricing_tier"),
                name="unique_default_per_course_tier",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepricing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pricing_tier__isnull", True)),
                fields=("course", "effective_date"),
                name="unique_course_pricing_no_tier",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepricing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pricing_tier__isnull", False)),
                fields=("course", "pricing_tier", "effective_date"),
                name="unique_course_pricing_with_tier",
            ),
        ),
    ]
