# Generated by Django 5.2.4 on 2025-07-24 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_rename_senior_project_pricing_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feepricing",
            name="finance_fee_pricing_34f0ed_idx",
        ),
        migrations.AlterUniqueTogether(
            name="feepricing",
            unique_together={("name", "fee_type", "effective_date")},
        ),
        migrations.AddField(
            model_name="feepricing",
            name="foreign_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fee amount for foreign students",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Foreign Amount",
            ),
        ),
        migrations.AddField(
            model_name="feepricing",
            name="local_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fee amount for local students",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Local Amount",
            ),
        ),
        migrations.RemoveField(
            model_name="feepricing",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="feepricing",
            name="pricing_tier",
        ),
    ]
