# Generated by Django 5.2.4 on 2025-07-28 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_add_ar_reconstruction_system"),
    ]

    operations = [
        # Rename the invoice line item table to match the model's db_table setting
        migrations.RunSQL(
            sql="ALTER TABLE finance_invoicelineitem RENAME TO finance_invoice_line_item;",
            reverse_sql="ALTER TABLE finance_invoice_line_item RENAME TO finance_invoicelineitem;",
        ),
    ]
