# Generated by Django 5.2.4 on 2025-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_rename_invoice_line_item_table"),
    ]

    operations = [
        # Make term_id nullable to support multi-term processing batches
        migrations.AlterField(
            model_name="arreconstructionbatch",
            name="term_id",
            field=models.CharField(
                blank=True,
                help_text="Academic term being processed (null for multi-term batches)",
                max_length=50,
                null=True,
                verbose_name="Term ID",
            ),
        ),
    ]
