# Generated by Django 5.2.4 on 2025-07-29 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_add_legacy_ipk_fields"),
        ("finance", "0018_add_notes_processing_fields"),
    ]

    operations = []
