# Generated by Django 5.2.4 on 2025-08-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0022_optimize_invoice_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountrule",
            name="applies_to_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HS", "High School (EHSS)"),
                    ("CERT", "Certificate Program"),
                    ("PREP", "Preparatory (IEAP/Foundation)"),
                    ("BA", "Bachelor's Degree"),
                    ("MA", "Master's Degree"),
                    ("PHD", "Doctoral Degree"),
                ],
                help_text="Academic cycle this rule applies to (empty = all cycles)",
                max_length=10,
                verbose_name="Applies to Cycle",
            ),
        ),
    ]
