# Generated by Django 5.2.4 on 2025-08-05 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0031_update_fee_pricing_for_documents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feepricing",
            name="finance_fee_is_mand_a2cb82_idx",
        ),
        migrations.RemoveField(
            model_name="discountrule",
            name="applies_to_schedule",
        ),
        migrations.AlterField(
            model_name="feeglmapping",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Registration Fee"),
                    ("APPLICATION", "Application Fee"),
                    ("LATE_PAYMENT", "Late Payment Fee"),
                    ("MATERIAL", "Material Fee"),
                    ("TECHNOLOGY", "Technology Fee"),
                    ("LIBRARY", "Library Fee"),
                    ("STUDENT_SERVICES", "Student Services Fee"),
                    ("GRADUATION", "Graduation Fee"),
                    ("DOCUMENT", "Document Fee"),
                    ("ID_CARD", "ID Card Fee"),
                    ("PARKING", "Parking Fee"),
                    ("OTHER", "Other Fee"),
                ],
                help_text="Type of fee this mapping applies to",
                max_length=20,
                verbose_name="Fee Type",
            ),
        ),
        migrations.AlterField(
            model_name="feepricing",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Registration Fee"),
                    ("APPLICATION", "Application Fee"),
                    ("LATE_PAYMENT", "Late Payment Fee"),
                    ("MATERIAL", "Material Fee"),
                    ("TECHNOLOGY", "Technology Fee"),
                    ("LIBRARY", "Library Fee"),
                    ("STUDENT_SERVICES", "Student Services Fee"),
                    ("GRADUATION", "Graduation Fee"),
                    ("DOCUMENT", "Document Fee"),
                    ("ID_CARD", "ID Card Fee"),
                    ("PARKING", "Parking Fee"),
                    ("OTHER", "Other Fee"),
                ],
                help_text="Category of this fee",
                max_length=20,
                verbose_name="Fee Type",
            ),
        ),
        migrations.AlterField(
            model_name="feepricing",
            name="is_mandatory",
            field=models.BooleanField(
                default=True,
                help_text="If true: automatically charged to all applicable students. If false: optional/on-request fee.",
                verbose_name="Is Mandatory",
            ),
        ),
        migrations.AlterField(
            model_name="feepricing",
            name="is_per_course",
            field=models.BooleanField(
                default=False,
                help_text="Charged once for EACH course enrollment (e.g., $10 per course for material fee)",
                verbose_name="Is Per Course",
            ),
        ),
        migrations.AlterField(
            model_name="feepricing",
            name="is_per_document",
            field=models.BooleanField(
                default=False,
                help_text="Charged for each document requested (e.g., $5 per transcript, $10 per certificate)",
                verbose_name="Is Per Document",
            ),
        ),
        migrations.AlterField(
            model_name="feepricing",
            name="is_per_term",
            field=models.BooleanField(
                default=False,
                help_text="Charged once per term regardless of course count (e.g., $50 registration fee per term)",
                verbose_name="Is Per Term",
            ),
        ),
        migrations.AddIndex(
            model_name="feepricing",
            index=models.Index(
                fields=["is_mandatory", "is_per_course", "is_per_term", "is_per_document"],
                name="finance_fee_is_mand_89d497_idx",
            ),
        ),
    ]
