# Generated by Django 5.2.5 on 2025-08-21 00:16

from decimal import Decimal

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0035_fix_legacy_receipt_mapping_nullable_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashiersession",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Whether this session is currently active",
                null=True,
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="cashiersession",
            name="opened_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="When session was opened",
                null=True,
                verbose_name="Opened At",
            ),
        ),
        migrations.AlterField(
            model_name="cashiersession",
            name="opening_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cash drawer opening balance",
                max_digits=10,
                null=True,
                verbose_name="Opening Balance",
            ),
        ),
        migrations.AlterField(
            model_name="cashiersession",
            name="session_number",
            field=models.CharField(
                blank=True,
                default="DEFAULT-001",
                help_text="Unique session identifier",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Session Number",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="legacy_receipt_id",
            field=models.CharField(
                blank=True,
                help_text="Full receipt ID with clerk information from legacy system",
                max_length=200,
                null=True,
                verbose_name="Legacy Receipt ID",
            ),
        ),
    ]
