# Generated by Django 5.2.4 on 2025-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0009_alter_studentphoto_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="alternate_gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("K", "Monk"), ("X", "Prefer not to say")],
                default="X",
                help_text="Gender to be used on official documents",
                max_length=1,
                verbose_name="Legal Gender",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="preferred_gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("K", "Monk"), ("X", "Prefer not to say")],
                default="X",
                max_length=1,
                verbose_name="Preferred Gender",
            ),
        ),
    ]
