# Generated by Django 5.2.4 on 2025-08-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("level_testing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potentialstudent",
            name="how_did_you_hear",
            field=models.CharField(
                blank=True,
                choices=[
                    ("friend", "My friend studied/studies here"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("at_school", "At my school"),
                    ("family", "From family"),
                    ("poster", "Outside poster/banner"),
                    ("other", "Other"),
                ],
                help_text="Marketing research: how you learned about our school",
                max_length=20,
                verbose_name="How Did You Hear About Us",
            ),
        ),
    ]
