# Generated by Django 5.2.4 on 2025-08-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("level_testing", "0002_update_how_did_you_hear_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="potentialstudent",
            name="last_english_study_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("studying_now", "Studying now in school"),
                    ("never_studied", "Never studied"),
                    ("3_months", "3 months ago"),
                    ("6_months", "6 months ago"),
                    ("over_1_year", "Over 1 year ago"),
                ],
                help_text="When you last studied English formally",
                max_length=20,
                null=True,
                verbose_name="When Did You Last Study English",
            ),
        ),
    ]
