# Generated by Django 5.2.4 on 2025-08-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("level_testing", "0003_add_last_english_study_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="potentialstudent",
            name="current_high_school",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NORTHBRIDGE", "Northbridge International School"),
                    ("ISPP", "International School of Phnom Penh"),
                    ("WESTLINE", "Westline School"),
                    ("ICAN", "iCAN British International School"),
                    ("LOGOS", "Logos International School"),
                    ("PUBLIC_HS", "Public High School"),
                    ("PRIVATE_HS", "Private High School"),
                    ("OTHER_HS", "Other High School"),
                ],
                help_text="High school you are currently attending",
                max_length=20,
                verbose_name="Current High School",
            ),
        ),
        migrations.AddField(
            model_name="potentialstudent",
            name="current_study_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "High School"),
                    ("university", "University"),
                    ("not_studying", "Not studying"),
                ],
                help_text="Your current educational status",
                max_length=20,
                verbose_name="Where are you currently studying?",
            ),
        ),
        migrations.AddField(
            model_name="potentialstudent",
            name="current_university",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BELTEI", "Beltei International University"),
                    ("NORTON", "Norton University"),
                    ("ROYAL", "Royal University of Phnom Penh"),
                    ("ZAMAN", "Zaman University"),
                    ("PUC", "Pannasastra University of Cambodia"),
                    ("IFL", "Institute for Foreign Languages (IFL)"),
                    ("BUILD_BRIGHT", "Build Bright University"),
                    ("CAMBODIA_MEKONG", "Cambodia Mekong University"),
                    ("OTHER_UNI", "Other University"),
                ],
                help_text="University you are currently attending",
                max_length=20,
                verbose_name="Current University",
            ),
        ),
        migrations.AddField(
            model_name="potentialstudent",
            name="work_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hotel_restaurant", "Hotel / Restaurant"),
                    ("medical_pharmacy", "Medical office / Pharmacy"),
                    ("small_company", "Small Company"),
                    ("not_working", "Not working"),
                ],
                help_text="Your current work field",
                max_length=20,
                verbose_name="Work Field",
            ),
        ),
    ]
