# Generated by Django 5.2.4 on 2025-07-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0004_alter_course_code"),
        ("enrollment", "0004_add_program_journey_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programenrollment",
            name="cycle",
            field=models.CharField(
                choices=[
                    ("HS", "High School (EHSS)"),
                    ("CERT", "Certificate Program"),
                    ("PREP", "Preparatory (IEAP/Foundation)"),
                    ("BA", "Bachelor's Degree"),
                    ("MA", "Master's Degree"),
                    ("PHD", "Doctoral Degree"),
                ],
                db_index=True,
                default="BA",
                help_text="Academic cycle or degree level",
                max_length=10,
                verbose_name="Cycle",
            ),
        ),
        migrations.AlterField(
            model_name="programenrollment",
            name="division",
            field=models.CharField(
                choices=[
                    ("LANG", "Language Programs"),
                    ("ACAD", "Academic Programs"),
                    ("PREP", "Preparatory Programs"),
                    ("PROF", "Professional Development"),
                ],
                db_index=True,
                default="ACAD",
                help_text="Academic division (Language/Academic/etc)",
                max_length=10,
                verbose_name="Division",
            ),
        ),
        migrations.AlterField(
            model_name="programtransition",
            name="transition_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="curriculum.term",
            ),
        ),
    ]
