# Generated by Django 5.2.4 on 2025-07-31 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0007_add_senior_project_group"),
        ("enrollment", "0008_add_program_transition_model"),
    ]

    operations = []
