# Generated by Django 5.2.4 on 2025-08-02 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0020_detect_transitions_with_active_majors"),
    ]

    operations = [
        migrations.AddField(
            model_name="programtransition",
            name="from_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitions_from",
                to="enrollment.programenrollment",
                verbose_name="From Program",
            ),
        ),
        migrations.AddField(
            model_name="programtransition",
            name="to_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitions_to",
                to="enrollment.programenrollment",
                verbose_name="To Program",
            ),
        ),
    ]
