# Generated by Django 5.2.5 on 2025-08-19 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0011_fix_academic_journey_start_term_nullable"),
        ("enrollment", "0023_alter_programtransition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicjourney",
            name="start_term",
            field=models.ForeignKey(
                blank=True,
                help_text="Term when this program period started",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journey_starts",
                to="curriculum.term",
                verbose_name="Start Term",
            ),
        ),
    ]
