# Generated by Django 5.2.5 on 2025-08-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0024_fix_academic_journey_start_term_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicjourney",
            name="start_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date when this program period started",
                null=True,
                verbose_name="Start Date",
            ),
        ),
    ]
