# Generated by Django 5.2.4 on 2025-07-15 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("people", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="positionassignment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="position_assignments",
                to="people.person",
                verbose_name="Person",
            ),
        ),
        migrations.AddField(
            model_name="positionassignment",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="accounts.position",
                verbose_name="Position",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department this role belongs to (leave blank for global roles)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="accounts.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="parent_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent role for permission inheritance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_roles",
                to="accounts.role",
                verbose_name="Parent Role",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Content type for object-level permissions",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Content Type",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department scope for this permission (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="accounts.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to="accounts.permission",
                verbose_name="Permission",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="accounts.role",
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_assignments",
                to="accounts.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teaching_assignments",
                to="people.teacherprofile",
                verbose_name="Teacher",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department context for this role assignment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="accounts.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assignments",
                to="accounts.role",
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["codename"], name="accounts_pe_codenam_3517e8_idx"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["content_type", "is_active"],
                name="accounts_pe_content_93512a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["authority_level", "is_active"],
                name="accounts_po_authori_f2cf6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["department", "is_active"],
                name="accounts_po_departm_5cd27e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["reports_to"], name="accounts_po_reports_6923fc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("title", "department")},
        ),
        migrations.AddIndex(
            model_name="positionassignment",
            index=models.Index(
                fields=["person", "start_date", "end_date"],
                name="accounts_po_person__dc6433_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="positionassignment",
            index=models.Index(
                fields=["position", "start_date", "end_date"],
                name="accounts_po_positio_46ac0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="positionassignment",
            index=models.Index(fields=["is_primary", "end_date"], name="accounts_po_is_prim_edf833_idx"),
        ),
        migrations.AddIndex(
            model_name="positionassignment",
            index=models.Index(fields=["delegates_to"], name="accounts_po_delegat_ee3e1e_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["role_type", "is_active"], name="accounts_ro_role_ty_193a9c_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["department", "is_active"],
                name="accounts_ro_departm_caed3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["parent_role"], name="accounts_ro_parent__d9ec2a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("name", "department")},
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(fields=["role", "is_active"], name="accounts_ro_role_id_3908c3_idx"),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["permission", "is_active"],
                name="accounts_ro_permiss_7ffa03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["department", "is_active"],
                name="accounts_ro_departm_01f455_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="accounts_ro_content_2695d3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission", "department", "content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(fields=["teacher", "is_active"], name="accounts_te_teacher_4a7673_idx"),
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(
                fields=["department", "is_active"],
                name="accounts_te_departm_a5077c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(fields=["start_date", "end_date"], name="accounts_te_start_d_fd51f7_idx"),
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(
                fields=["authorized_levels", "minimum_degree"],
                name="accounts_te_authori_3f1a8e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachingassignment",
            unique_together={("teacher", "department")},
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["user", "is_active"], name="accounts_us_user_id_2517ab_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role", "is_active"], name="accounts_us_role_id_327ba4_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["department", "is_active"],
                name="accounts_us_departm_05d7e4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role", "department")},
        ),
    ]
