# Shared Traefik instance that routes to both dev and eval stacks
name: traefik-router

networks:
  web:
    external: true  # Create once: docker network create web

volumes:
  letsencrypt: {}

services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"  # Dashboard
    command:
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      
      # Let's Encrypt for dev domains
      - --certificatesresolvers.letsencrypt.acme.email=admin@pucsr.edu.kh
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      
      # API
      - --api.dashboard=true
      - --log.level=INFO
      - --accesslog=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./compose/traefik/certs:/certs:ro
      - ./compose/traefik/dynamic:/etc/traefik/dynamic:ro
      - letsencrypt:/letsencrypt
      - ./logs/traefik:/var/log/traefik
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.pucsr.edu.kh`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=admin-auth@file"