# Prometheus configuration for Naga SIS monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Django backend application metrics
  - job_name: 'django-backend'
    static_configs:
      - targets: ['django:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true

  # Staff-Web V2 React frontend metrics
  - job_name: 'staff-web-frontend'
    static_configs:
      - targets: ['staff-web:80']
    scrape_interval: 30s
    metrics_path: /metrics

  # Celery worker metrics
  - job_name: 'celery-worker'
    static_configs:
      - targets: ['celery-worker:9540']
    scrape_interval: 30s
    metrics_path: /metrics

  # Celery beat scheduler metrics
  - job_name: 'celery-beat'
    static_configs:
      - targets: ['celery-beat:9540']
    scrape_interval: 60s
    metrics_path: /metrics

  # Traefik reverse proxy metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Uptime Kuma monitoring
  - job_name: 'uptime-kuma'
    static_configs:
      - targets: ['uptime-kuma:3001']
    scrape_interval: 60s
    metrics_path: /metrics

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Alertmanager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s
    metrics_path: /metrics

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'backend:8000'
        - 'frontend:8080'
    scrape_interval: 15s
    metrics_path: /health
    params:
      format: ['prometheus']

  # External services monitoring (if applicable)
  - job_name: 'external-apis'
    static_configs:
      - targets: []  # Add external API endpoints here
    scrape_interval: 60s
    metrics_path: /health
    scheme: https

# Remote write configuration (for production)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB