# Generated by Django 5.2.4 on 2025-07-31 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0006_add_senior_project_csv_fields"),
        ("people", "0009_alter_studentphoto_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seniorprojectgroup",
            name="advisor",
            field=models.ForeignKey(
                help_text="Faculty member supervising this project",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curriculum_advised_senior_projects",
                to="people.teacherprofile",
                verbose_name="Faculty Advisor",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectgroup",
            name="course",
            field=models.ForeignKey(
                help_text="Course this senior project is associated with",
                limit_choices_to={"is_senior_project": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curriculum_senior_project_groups",
                to="curriculum.course",
                verbose_name="Senior Project Course",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectgroup",
            name="students",
            field=models.ManyToManyField(
                help_text="Students participating in this senior project (1-5 students)",
                related_name="curriculum_senior_project_groups",
                to="people.studentprofile",
                verbose_name="Group Members",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectgroup",
            name="term",
            field=models.ForeignKey(
                help_text="Term when this project is being conducted",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curriculum_senior_project_groups",
                to="curriculum.term",
                verbose_name="Term",
            ),
        ),
    ]
