# Generated by Django 5.2.4 on 2025-08-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0008_move_discount_rule_to_discounts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seniorprojectgroup",
            name="graduation_date",
        ),
        migrations.RemoveField(
            model_name="seniorprojectgroup",
            name="is_graduated",
        ),
        migrations.RemoveField(
            model_name="seniorprojectgroup",
            name="registration_date",
        ),
        migrations.RemoveField(
            model_name="seniorprojectgroup",
            name="registration_term",
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Course code (e.g., 'ENGL-110', 'MATH-101'). Multiple versions allowed with different effective dates.",
                max_length=15,
                verbose_name="Course Code",
            ),
        ),
    ]
