# Generated by Django 5.2.4 on 2025-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("CLASS", "Classroom"),
                    ("COMP", "Computer Lab"),
                    ("LANG", "Language Lab"),
                    ("CONFERENCE", "Conference Room"),
                    ("MEETING", "Meeting Room"),
                    ("OFFICE", "Office"),
                    ("OTHER", "Other"),
                ],
                default="CLASS",
                help_text="Type of room for scheduling purposes",
                max_length=20,
                verbose_name="Room Type",
            ),
        ),
    ]
