# Generated by Django 5.2.4 on 2025-07-18 05:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_migrate_student_audit_logs"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="room",
            managers=[],
        ),
        migrations.RemoveIndex(
            model_name="studentactivitylog",
            name="common_stud_visibil_8f4d3c_idx",
        ),
        migrations.RemoveIndex(
            model_name="systemauditlog",
            name="common_syst_target__05c677_idx",
        ),
        migrations.AddField(
            model_name="systemauditlog",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                help_text="Type of the target object",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Content Type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemauditlog",
            name="object_id",
            field=models.PositiveIntegerField(
                default=1,
                help_text="ID of the specific object that was affected",
                verbose_name="Object ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentactivitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("CLASS_ENROLLMENT", "Class Enrollment"),
                    ("CLASS_WITHDRAWAL", "Class Withdrawal"),
                    ("CLASS_COMPLETION", "Class Completion"),
                    ("LANGUAGE_PROMOTION", "Language Level Promotion"),
                    ("LANGUAGE_LEVEL_SKIP", "Language Level Skip"),
                    ("LANGUAGE_PROGRAM_TRANSFER", "Language Program Transfer"),
                    ("GRADE_ASSIGNMENT", "Grade Assignment"),
                    ("GRADE_CHANGE", "Grade Change"),
                    ("GRADUATION", "Graduation Recorded"),
                    ("PROGRAM_ENROLLMENT", "Program Enrollment"),
                    ("PROGRAM_WITHDRAWAL", "Program Withdrawal"),
                    ("STUDENT_STATUS_CHANGE", "Student Status Change"),
                    ("MONK_STATUS_CHANGE", "Monk Status Change"),
                    ("MANAGEMENT_OVERRIDE", "Management Override Applied"),
                    ("REPEAT_PREVENTION_OVERRIDE", "Repeat Prevention Override"),
                    ("PREREQUISITE_OVERRIDE", "Prerequisite Override"),
                    ("CAPACITY_OVERRIDE", "Capacity Override"),
                    ("ATTENDANCE_RECORD", "Attendance Record"),
                    ("DOCUMENT_REQUEST", "Document Request"),
                    ("SCHOLARSHIP_ASSIGNED", "Scholarship Assigned"),
                    ("SCHOLARSHIP_REVOKED", "Scholarship Revoked"),
                    ("PROFILE_CREATE", "Student Profile Created"),
                    ("PROFILE_UPDATE", "Student Profile Updated"),
                    ("PROFILE_MERGE", "Student Profiles Merged"),
                ],
                db_index=True,
                help_text="Type of activity performed",
                max_length=40,
                verbose_name="Activity Type",
            ),
        ),
        migrations.AlterField(
            model_name="systemauditlog",
            name="target_app",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use content_type instead",
                max_length=50,
                null=True,
                verbose_name="Target App",
            ),
        ),
        migrations.AlterField(
            model_name="systemauditlog",
            name="target_model",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use content_type instead",
                max_length=50,
                null=True,
                verbose_name="Target Model",
            ),
        ),
        migrations.AlterField(
            model_name="systemauditlog",
            name="target_object_id",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use object_id instead",
                max_length=100,
                null=True,
                verbose_name="Target Object ID",
            ),
        ),
        migrations.AddIndex(
            model_name="systemauditlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="common_syst_content_7b22cf_idx",
            ),
        ),
    ]
