# Generated by Django 5.2.4 on 2025-08-05 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0023_alter_programtransition_options_and_more"),
        ("grading", "0003_classpartgrade_created_by_classpartgrade_updated_by_and_more"),
        ("scheduling", "0005_classpart_template_derived"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="classpartgrade",
            index=models.Index(fields=["grade_source", "grade_status"], name="grading_cla_grade_s_450aa9_idx"),
        ),
        migrations.AddIndex(
            model_name="classpartgrade",
            index=models.Index(fields=["entered_by", "entered_at"], name="grading_cla_entered_58d5c5_idx"),
        ),
        migrations.AddIndex(
            model_name="classpartgrade",
            index=models.Index(
                fields=["enrollment", "class_part", "grade_status"], name="grading_cla_enrollm_75e4d6_idx"
            ),
        ),
    ]
