# Generated by Django 5.2.4 on 2025-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("level_testing", "0004_add_conditional_education_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="potentialstudent",
            name="last_english_level",
        ),
        migrations.RemoveField(
            model_name="potentialstudent",
            name="last_english_textbook",
        ),
        migrations.AddField(
            model_name="potentialstudent",
            name="english_level_self_assessment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "0 - No English"),
                    ("1", "1 - Basic English"),
                    ("2", "2 - Between basic and intermediate"),
                    ("3", "3 - Intermediate English"),
                    ("4", "4 - High Intermediate"),
                    ("5", "5 - Start of advanced English skills"),
                ],
                default="0",
                help_text="Self-assessment of current English proficiency level",
                max_length=1,
                verbose_name="What do you think your current level of English is?",
            ),
        ),
        migrations.AlterField(
            model_name="potentialstudent",
            name="last_english_school",
            field=models.CharField(
                blank=True,
                help_text="Previous English language institution",
                max_length=100,
                verbose_name="Where did you study?",
            ),
        ),
        migrations.AlterField(
            model_name="potentialstudent",
            name="last_english_study_period",
            field=models.CharField(
                choices=[
                    ("studying_now", "Studying now in school"),
                    ("never_studied", "Never studied"),
                    ("3_months", "3 months ago"),
                    ("6_months", "6 months ago"),
                    ("over_1_year", "Over 1 year ago"),
                ],
                default="never_studied",
                help_text="When you last studied English formally",
                max_length=20,
                verbose_name="When did you last study English?",
            ),
        ),
        migrations.AlterField(
            model_name="potentialstudent",
            name="preferred_gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("K", "Monk"), ("X", "Prefer not to say")],
                help_text="Gender identity preference",
                max_length=1,
                verbose_name="Preferred Gender",
            ),
        ),
        migrations.AlterField(
            model_name="potentialstudent",
            name="preferred_time_slot",
            field=models.CharField(
                choices=[
                    ("MORNING", "Between 8-11am (3 hours per day)"),
                    ("AFTERNOON", "Between 2-5pm (3 hours per day)"),
                    ("EVENING", "Between 6-9pm (1.5 or 3 hours per day)"),
                    ("SATURDAY", "On Saturday afternoons (4 hours)"),
                    ("SUNDAY", "On Sunday mornings (4 hours)"),
                ],
                help_text="Preferred study schedule",
                max_length=20,
                verbose_name="Preferred Time Slot",
            ),
        ),
    ]
