# Generated by Django 5.2.4 on 2025-08-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("level_testing", "0006_add_test_completion_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="potentialstudent",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                help_text="Name of emergency contact person",
                max_length=100,
                verbose_name="Emergency Contact Name",
            ),
        ),
        migrations.AddField(
            model_name="potentialstudent",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number of emergency contact",
                max_length=20,
                verbose_name="Emergency Contact Phone",
            ),
        ),
        migrations.AddField(
            model_name="potentialstudent",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FATHER", "Father"),
                    ("MOTHER", "Mother"),
                    ("SPOUSE", "Spouse"),
                    ("PARTNER", "Partner"),
                    ("SIBLING", "Sibling"),
                    ("GRANDPARENT", "Grandparent"),
                    ("GUARDIAN", "Legal Guardian"),
                    ("FRIEND", "Friend"),
                    ("OTHER", "Other"),
                ],
                help_text="Relationship to emergency contact",
                max_length=15,
                verbose_name="Emergency Contact Relationship",
            ),
        ),
    ]
