# Generated by Django 5.2.5 on 2025-08-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("level_testing", "0008_add_test_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potentialstudent",
            name="last_english_date",
            field=models.DateField(
                blank=True,
                help_text="DEPRECATED - Use last_english_study_period instead",
                null=True,
                verbose_name="Last English Study Date",
            ),
        ),
    ]
