global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # "first_rules.yml"
  # "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Django application (if django-prometheus is enabled)
  - job_name: 'django-naga-sis'
    static_configs:
      - targets: ['new_naga_sis_backend_local_django:8000']
    metrics_path: '/metrics/'
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['new_naga_sis_backend_local_redis:6379']
    scrape_interval: 30s

  # PostgreSQL metrics (if postgres_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['new_naga_sis_backend_local_postgres:5432']
    scrape_interval: 30s

  # Netdata metrics
  - job_name: 'netdata'
    static_configs:
      - targets: ['naga-netdata:19999']
    metrics_path: '/api/v1/allmetrics'
    params:
      format: ['prometheus']
    scrape_interval: 30s
