# Generated by Django 5.2.4 on 2025-07-24 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_add_separated_pricing_models"),
        ("finance", "0005_make_pricing_tier_optional"),
    ]

    operations = []
