# Generated by Django 5.2.4 on 2025-07-24 13:18

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_merge_20250724_2002"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="coursefixedpricing",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="defaultpricing",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="readingclasspricing",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="seniorprojectcourse",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="seniorprojectpricing",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="coursefixedpricing",
            new_name="finance_cou_course__c7f8f6_idx",
            old_name="finance_course_course__84e3c1_idx",
        ),
        migrations.RenameIndex(
            model_name="coursefixedpricing",
            new_name="finance_cou_effecti_ee431d_idx",
            old_name="finance_course_effecti_a6c4b7_idx",
        ),
        migrations.RenameIndex(
            model_name="defaultpricing",
            new_name="finance_def_cycle_i_71c147_idx",
            old_name="finance_defaul_cycle_i_7e1b5c_idx",
        ),
        migrations.RenameIndex(
            model_name="defaultpricing",
            new_name="finance_def_effecti_e075fc_idx",
            old_name="finance_defaul_effecti_6b0d2a_idx",
        ),
        migrations.RenameIndex(
            model_name="readingclasspricing",
            new_name="finance_rea_cycle_i_5b7d30_idx",
            old_name="finance_readin_cycle_i_3a9f4c_idx",
        ),
        migrations.RenameIndex(
            model_name="readingclasspricing",
            new_name="finance_rea_effecti_776e92_idx",
            old_name="finance_readin_effecti_2b8e7d_idx",
        ),
        migrations.RenameIndex(
            model_name="seniorprojectpricing",
            new_name="finance_sen_tier_462e6e_idx",
            old_name="finance_senior_tier_7f9a1b_idx",
        ),
        migrations.RenameIndex(
            model_name="seniorprojectpricing",
            new_name="finance_sen_effecti_a7bb6e_idx",
            old_name="finance_senior_effecti_c5d8e2_idx",
        ),
        migrations.AddField(
            model_name="coursefixedpricing",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AddField(
            model_name="defaultpricing",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AddField(
            model_name="readingclasspricing",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AddField(
            model_name="seniorprojectcourse",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AddField(
            model_name="seniorprojectpricing",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AlterField(
            model_name="coursefixedpricing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the record was created",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="coursefixedpricing",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="coursefixedpricing",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this record has been soft deleted",
                verbose_name="Is deleted",
            ),
        ),
        migrations.AlterField(
            model_name="coursefixedpricing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the record was last updated",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="coursefixedpricing",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="defaultpricing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the record was created",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="defaultpricing",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="defaultpricing",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this record has been soft deleted",
                verbose_name="Is deleted",
            ),
        ),
        migrations.AlterField(
            model_name="defaultpricing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the record was last updated",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="defaultpricing",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="readingclasspricing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the record was created",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="readingclasspricing",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="readingclasspricing",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this record has been soft deleted",
                verbose_name="Is deleted",
            ),
        ),
        migrations.AlterField(
            model_name="readingclasspricing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the record was last updated",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="readingclasspricing",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectcourse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the record was created",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectcourse",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectcourse",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this record has been soft deleted",
                verbose_name="Is deleted",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectcourse",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the record was last updated",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectcourse",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectpricing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the record was created",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectpricing",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectpricing",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this record has been soft deleted",
                verbose_name="Is deleted",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectpricing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the record was last updated",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="seniorprojectpricing",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
    ]
