# Generated by Django 5.2.4 on 2025-07-24 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_add_deleted_at_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seniorprojectpricing",
            name="foreign_price",
        ),
        migrations.RemoveField(
            model_name="seniorprojectpricing",
            name="total_price",
        ),
        migrations.AddField(
            model_name="seniorprojectcourse",
            name="allows_groups",
            field=models.BooleanField(
                default=True,
                help_text="Whether this project type allows group work (TESOL is individual only)",
                verbose_name="Allows Groups",
            ),
        ),
        migrations.AddField(
            model_name="seniorprojectcourse",
            name="major_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the major this project serves (e.g., Business Administration, International Relations)",
                max_length=100,
                null=True,
                verbose_name="Major Name",
            ),
        ),
        migrations.AddField(
            model_name="seniorprojectcourse",
            name="project_code",
            field=models.CharField(
                blank=True,
                help_text="Project identification code (e.g., BUS-489, IR-489, FIN-489, THM-433)",
                max_length=20,
                null=True,
                verbose_name="Project Code",
            ),
        ),
        migrations.AddField(
            model_name="seniorprojectpricing",
            name="foreign_individual_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price each foreign student pays individually (NOT split among group)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Foreign Individual Price",
            ),
        ),
        migrations.AddField(
            model_name="seniorprojectpricing",
            name="individual_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price each student pays individually (NOT split among group)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Individual Price",
            ),
        ),
    ]
