# Generated by Django 5.2.4 on 2025-07-28 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0012_add_reconciliation_models"),
    ]

    operations = []
