# Generated by Django 5.2.4 on 2025-07-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0020_remove_coursepricing_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reconciliationadjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[
                    ("PRICING", "Pricing Variance"),
                    ("MISSING_ENR", "Missing Enrollment"),
                    ("MISSING_PAY", "Missing Payment"),
                    ("DUPLICATE", "Duplicate Payment"),
                    ("CURRENCY", "Currency Difference"),
                    ("CLERICAL", "Clerical Error"),
                    ("DISCOUNT", "Discount Applied"),
                    ("FEE_ADJ", "Fee Adjustment"),
                    ("TIMING", "Timing Difference"),
                    ("SCHOLARSHIP_VAR", "Scholarship Application Variance"),
                    ("SCHOLARSHIP_OVER", "Scholarship Over-Applied"),
                    ("SCHOLARSHIP_UNDER", "Scholarship Under-Applied"),
                    ("MISSING_SCHOLARSHIP", "Missing Scholarship Record"),
                ],
                max_length=20,
                verbose_name="Adjustment Type",
            ),
        ),
        migrations.AlterField(
            model_name="reconciliationstatus",
            name="pricing_method_applied",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFAULT", "Default Pricing"),
                    ("FIXED", "Course Fixed Pricing"),
                    ("SENIOR", "Senior Project Pricing"),
                    ("READING", "Reading Class Pricing"),
                    ("HISTORICAL", "Historical Pattern Match"),
                    ("SCHOLARSHIP", "Scholarship Verification"),
                    ("MANUAL", "Manual Override"),
                    ("HYBRID", "Hybrid/Multiple Methods"),
                ],
                max_length=20,
                null=True,
                verbose_name="Pricing Method Applied",
            ),
        ),
        migrations.AlterField(
            model_name="reconciliationstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("FULLY_RECONCILED", "Fully Reconciled"),
                    ("AUTO_ALLOCATED", "Auto-Allocated"),
                    ("SCHOLARSHIP_VERIFIED", "Scholarship Verified"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("EXCEPTION_ERROR", "Exception/Error"),
                    ("UNMATCHED", "Unmatched"),
                ],
                default="UNMATCHED",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
