# Generated by Django 5.2.4 on 2025-08-03 01:32

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0028_update_invoicelineitem_types"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="administrativefeeconfig",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="documentexcessfee",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_status_issue_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_student_term_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_overdue_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_amounts_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoicelineitem",
            name="finance_line_inv_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoicelineitem",
            name="finance_line_enrollment_idx",
        ),
        migrations.RenameIndex(
            model_name="administrativefeeconfig",
            new_name="finance_adm_cycle_t_6b5d86_idx",
            old_name="finance_adm_cycle_t_3f8a9c_idx",
        ),
        migrations.RenameIndex(
            model_name="administrativefeeconfig",
            new_name="finance_adm_effecti_2c5a2c_idx",
            old_name="finance_adm_effecti_2b5c7d_idx",
        ),
        migrations.RenameIndex(
            model_name="administrativefeeconfig",
            new_name="finance_adm_cycle_t_dbfdcf_idx",
            old_name="finance_adm_cycle_t_9a2e4f_idx",
        ),
        migrations.RenameIndex(
            model_name="documentexcessfee",
            new_name="finance_doc_invoice_0d2045_idx",
            old_name="finance_doc_invoice_8d1b3e_idx",
        ),
        migrations.RenameIndex(
            model_name="documentexcessfee",
            new_name="finance_doc_documen_7d576f_idx",
            old_name="finance_doc_documen_6f2a9c_idx",
        ),
        migrations.AddField(
            model_name="administrativefeeconfig",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AddField(
            model_name="administrativefeeconfig",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Indicates if this record has been soft deleted", verbose_name="Is deleted"
            ),
        ),
        migrations.AddField(
            model_name="documentexcessfee",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AddField(
            model_name="documentexcessfee",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Indicates if this record has been soft deleted", verbose_name="Is deleted"
            ),
        ),
    ]
