# Generated by Django 5.2.5 on 2025-08-19 21:14

from decimal import Decimal

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0034_fix_cashier_session_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashiersession",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, help_text="When session was closed", null=True, verbose_name="Closed At"
            ),
        ),
        migrations.AlterField(
            model_name="cashiersession",
            name="closing_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cash drawer closing balance",
                max_digits=10,
                null=True,
                verbose_name="Closing Balance",
            ),
        ),
        migrations.AlterField(
            model_name="cashiersession",
            name="expected_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Expected balance based on transactions",
                max_digits=10,
                null=True,
                verbose_name="Expected Balance",
            ),
        ),
        migrations.AlterField(
            model_name="cashiersession",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this session is currently active", verbose_name="Is Active"
            ),
        ),
        migrations.AlterField(
            model_name="cashiersession",
            name="opened_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When session was opened", verbose_name="Opened At"
            ),
        ),
        migrations.AlterField(
            model_name="cashiersession",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cash drawer opening balance",
                max_digits=10,
                verbose_name="Opening Balance",
            ),
        ),
        migrations.AlterField(
            model_name="cashiersession",
            name="session_number",
            field=models.CharField(
                default="DEFAULT-001",
                help_text="Unique session identifier",
                max_length=50,
                unique=True,
                verbose_name="Session Number",
            ),
        ),
        migrations.AlterField(
            model_name="legacyreceiptmapping",
            name="legacy_ipk",
            field=models.IntegerField(
                blank=True,
                help_text="Original IPK primary key from receipt_headers - TRUE unique identifier",
                null=True,
                verbose_name="Legacy IPK",
            ),
        ),
        migrations.AlterField(
            model_name="legacyreceiptmapping",
            name="parsed_authority",
            field=models.CharField(
                blank=True,
                help_text="Authority/approver parsed from notes",
                max_length=100,
                null=True,
                verbose_name="Parsed Authority",
            ),
        ),
        migrations.AlterField(
            model_name="legacyreceiptmapping",
            name="parsed_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason parsed from notes",
                max_length=200,
                null=True,
                verbose_name="Parsed Reason",
            ),
        ),
    ]
