# Generated by Django 5.2.6 on 2025-09-26 15:51

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_add_missing_legacy_ipk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="legacy_ipk",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Identity Primary Key from legacy system for change tracking",
                null=True,
                verbose_name="Legacy System IPK",
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this record has been soft deleted",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was marked as deleted",
                        null=True,
                        verbose_name="Deleted at",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("SPOUSE", "Spouse"),
                            ("PARTNER", "Partner"),
                            ("SIBLING", "Sibling"),
                            ("GRANDPARENT", "Grandparent"),
                            ("GUARDIAN", "Legal Guardian"),
                            ("FRIEND", "Friend"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=40,
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        blank=True,
                        help_text="Can include multiple numbers separated by commas or slashes",
                        max_length=100,
                    ),
                ),
                ("secondary_phone", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "is_emergency_contact",
                    models.BooleanField(default=False, help_text="Call for medical emergencies, accidents"),
                ),
                (
                    "is_general_contact",
                    models.BooleanField(default=False, help_text="Call for misbehavior, absences, general issues"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="people.person"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["name"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="EmergencyContact",
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_emergency_contact", True), ("is_general_contact", True), _connector="OR"),
                name="contact_must_have_purpose",
            ),
        ),
    ]
