# Generated by Django 5.2.6 on 2025-09-26 21:01

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_alter_studentprofile_legacy_ipk_contact_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="khmer_name_approximated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the name was approximated",
                null=True,
                verbose_name="Khmer Name Approximated At",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="khmer_name_components",
            field=models.JSONField(
                blank=True,
                help_text="Decomposed name components for debugging",
                null=True,
                verbose_name="Khmer Name Components",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="khmer_name_confidence",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Confidence score (0.00-1.00) for approximated names",
                max_digits=3,
                verbose_name="Khmer Name Confidence",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="khmer_name_source",
            field=models.CharField(
                choices=[
                    ("user", "User Provided"),
                    ("approximated", "System Approximated"),
                    ("legacy", "Legacy Data"),
                    ("verified", "Verified by User"),
                    ("import", "Imported from External Source"),
                ],
                default="legacy",
                help_text="Source of the Khmer name data",
                max_length=20,
                verbose_name="Khmer Name Source",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="khmer_name_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When user verified the name", null=True, verbose_name="Khmer Name Verified At"
            ),
        ),
        migrations.CreateModel(
            name="KhmerNamePattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this record has been soft deleted",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was marked as deleted",
                        null=True,
                        verbose_name="Deleted at",
                    ),
                ),
                (
                    "english_component",
                    models.CharField(
                        db_index=True,
                        help_text="English name component (e.g., 'sovann', 'dara')",
                        max_length=100,
                        verbose_name="English Component",
                    ),
                ),
                (
                    "normalized_component",
                    models.CharField(
                        db_index=True,
                        help_text="Lowercase, normalized version for matching",
                        max_length=100,
                        verbose_name="Normalized Component",
                    ),
                ),
                (
                    "limon_pattern",
                    models.CharField(
                        help_text="LIMON representation of the component", max_length=255, verbose_name="LIMON Pattern"
                    ),
                ),
                (
                    "unicode_pattern",
                    models.CharField(
                        help_text="Unicode Khmer representation", max_length=255, verbose_name="Unicode Pattern"
                    ),
                ),
                (
                    "frequency",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Frequency of this pattern (0.00-1.00)",
                        max_digits=3,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "occurrence_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this pattern was observed",
                        verbose_name="Occurrence Count",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="Confidence in this pattern (0.00-1.00)",
                        max_digits=3,
                        verbose_name="Confidence Score",
                    ),
                ),
                (
                    "variants",
                    models.JSONField(
                        default=list,
                        help_text="Alternative spellings of the English component",
                        verbose_name="Variants",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this pattern has been verified by users",
                        verbose_name="Is Verified",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khmer Name Pattern",
                "verbose_name_plural": "Khmer Name Patterns",
                "ordering": ["-frequency", "-occurrence_count"],
                "indexes": [
                    models.Index(fields=["normalized_component"], name="people_khme_normali_ee3862_idx"),
                    models.Index(fields=["frequency", "confidence_score"], name="people_khme_frequen_6d4198_idx"),
                    models.Index(fields=["is_verified"], name="people_khme_is_veri_45d51a_idx"),
                ],
                "unique_together": {("english_component", "limon_pattern")},
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="KhmerNameCorrection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this record has been soft deleted",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was marked as deleted",
                        null=True,
                        verbose_name="Deleted at",
                    ),
                ),
                (
                    "original_khmer_name",
                    models.CharField(
                        blank=True,
                        help_text="Original Khmer name before correction",
                        max_length=255,
                        verbose_name="Original Khmer Name",
                    ),
                ),
                (
                    "corrected_khmer_name",
                    models.CharField(
                        help_text="User-provided correct Khmer name",
                        max_length=255,
                        verbose_name="Corrected Khmer Name",
                    ),
                ),
                (
                    "original_english_name",
                    models.CharField(
                        blank=True,
                        help_text="English name at time of correction",
                        max_length=255,
                        verbose_name="Original English Name",
                    ),
                ),
                (
                    "correction_source",
                    models.CharField(
                        choices=[
                            ("mobile_app", "Mobile App"),
                            ("web_interface", "Web Interface"),
                            ("admin", "Admin Interface"),
                            ("import", "Data Import"),
                            ("api", "API Submission"),
                        ],
                        help_text="Source of the correction",
                        max_length=50,
                        verbose_name="Correction Source",
                    ),
                ),
                (
                    "confidence_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Impact on pattern confidence scores",
                        max_digits=3,
                        null=True,
                        verbose_name="Confidence Impact",
                    ),
                ),
                (
                    "patterns_learned",
                    models.JSONField(
                        blank=True,
                        help_text="New patterns extracted from this correction",
                        null=True,
                        verbose_name="Patterns Learned",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When correction was verified", null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person whose name was corrected",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.person",
                        verbose_name="Person",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who verified this correction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_corrections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khmer Name Correction",
                "verbose_name_plural": "Khmer Name Corrections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["person", "created_at"], name="people_khme_person__2df775_idx"),
                    models.Index(fields=["correction_source"], name="people_khme_correct_f77c96_idx"),
                    models.Index(fields=["verified_at"], name="people_khme_verifie_68d042_idx"),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
