# Generated by Django 5.2.4 on 2025-07-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="term_type",
            field=models.CharField(
                choices=[
                    ("ENG A", "English Term A"),
                    ("ENG B", "English Term B"),
                    ("BA", "BA Term"),
                    ("MA", "MA Term"),
                    ("X", "Special Term"),
                ],
                db_index=True,
                help_text="Type of academic term",
                max_length=20,
                verbose_name="Term Type",
            ),
        ),
    ]
