# Generated by Django 5.2.4 on 2025-07-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0003_alter_term_term_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Course code (e.g., 'ENG101', 'MATH201'). Multiple versions allowed with different effective dates.",
                max_length=15,
                verbose_name="Course Code",
            ),
        ),
    ]
