# Generated by Django 5.2.4 on 2025-07-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0004_alter_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="program_type",
            field=models.CharField(
                choices=[("ACADEMIC", "Academic Degree Program"), ("LANGUAGE", "Language Program")],
                db_index=True,
                default="ACADEMIC",
                help_text="Distinguishes between ACADEMIC (degree-granting programs like BA, MBA, MEd) and LANGUAGE (non-degree programs like IEAP, GESL, EHSS)",
                max_length=20,
                verbose_name="Program Type",
            ),
        ),
    ]
