# Generated by Django 5.2.4 on 2025-07-31 16:00
# Migration to add CSV import fields to SeniorProjectGroup model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0005_alter_major_program_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="seniorprojectgroup",
            name="registration_date",
            field=models.DateField(
                blank=True,
                help_text="Date when students were first registered for the senior project",
                null=True,
                verbose_name="Registration Date",
            ),
        ),
        migrations.AddField(
            model_name="seniorprojectgroup",
            name="registration_term",
            field=models.ForeignKey(
                blank=True,
                help_text="Term that contains the registration date (automatically determined)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registered_senior_projects",
                to="curriculum.term",
                verbose_name="Registration Term",
            ),
        ),
        migrations.AddField(
            model_name="seniorprojectgroup",
            name="graduation_date",
            field=models.DateField(
                blank=True,
                help_text="Date when students graduated (from CSV data)",
                null=True,
                verbose_name="Graduation Date",
            ),
        ),
        migrations.AddField(
            model_name="seniorprojectgroup",
            name="is_graduated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the students in this group have graduated",
                verbose_name="Is Graduated",
            ),
        ),
    ]
