# Generated by Django 5.2.4 on 2025-08-02 05:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0007_add_senior_project_group"),
    ]

    operations = [
        # These fields don't exist in the database, so commenting out
        # migrations.RemoveField(
        #     model_name='seniorprojectgroup',
        #     name='graduation_date',
        # ),
        # migrations.RemoveField(
        #     model_name='seniorprojectgroup',
        #     name='is_graduated',
        # ),
        # migrations.RemoveField(
        #     model_name='seniorprojectgroup',
        #     name='registration_date',
        # ),
        # migrations.RemoveField(
        #     model_name='seniorprojectgroup',
        #     name='registration_term',
        # ),
    ]
