# Generated by Django 5.2.5 on 2025-08-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0009_remove_seniorprojectgroup_graduation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseparttemplate",
            name="part_type",
            field=models.CharField(
                choices=[
                    ("MAIN", "Main Class"),
                    ("LECTURE", "Lecture"),
                    ("DISCUSSION", "Discussion"),
                    ("LAB", "Laboratory"),
                    ("COMPUTER", "Computer Lab"),
                    ("WORKSHOP", "Workshop"),
                    ("TUTORIAL", "Tutorial"),
                    ("PROJECT", "Project"),
                    ("GRAMMAR", "Grammar"),
                    ("CONVERSATION", "Conversation"),
                    ("WRITING", "Writing"),
                    ("READING", "Reading"),
                    ("LISTENING", "Listening"),
                    ("SPEAKING", "Speaking"),
                    ("VENTURES", "Ventures"),
                    ("OTHER", "Other"),
                ],
                default="MAIN",
                help_text="Type of class component",
                max_length=15,
                verbose_name="Part Type",
            ),
        ),
    ]
