# Generated by Django 5.2.4 on 2025-07-15 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic_records", "0001_initial"),
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrequest",
            name="student",
            field=models.ForeignKey(
                help_text="Student requesting the document",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_requests",
                to="people.studentprofile",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="documentrequestcomment",
            name="author",
            field=models.ForeignKey(
                help_text="User who wrote this comment",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="documentrequestcomment",
            name="document_request",
            field=models.ForeignKey(
                help_text="Request this comment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="academic_records.documentrequest",
                verbose_name="Document Request",
            ),
        ),
        migrations.AddIndex(
            model_name="documenttypeconfig",
            index=models.Index(fields=["code"], name="academic_re_code_249125_idx"),
        ),
        migrations.AddIndex(
            model_name="documenttypeconfig",
            index=models.Index(fields=["category", "is_active"], name="academic_re_categor_02b24e_idx"),
        ),
        migrations.AddIndex(
            model_name="documenttypeconfig",
            index=models.Index(fields=["display_order"], name="academic_re_display_871231_idx"),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="document_type",
            field=models.ForeignKey(
                help_text="Type of document being requested",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="academic_records.documenttypeconfig",
                verbose_name="Document Type",
            ),
        ),
        migrations.AddField(
            model_name="documentusagetracker",
            name="document_type",
            field=models.ForeignKey(
                help_text="Document type this usage applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_records",
                to="academic_records.documenttypeconfig",
                verbose_name="Document Type",
            ),
        ),
        migrations.AddField(
            model_name="documentusagetracker",
            name="student",
            field=models.ForeignKey(
                help_text="Student this usage record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_usage",
                to="people.studentprofile",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="document_request",
            field=models.ForeignKey(
                help_text="Request that generated this document",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_documents",
                to="academic_records.documentrequest",
                verbose_name="Document Request",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="generated_by",
            field=models.ForeignKey(
                help_text="User who generated this document",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_generated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Generated By",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="student",
            field=models.ForeignKey(
                help_text="Student this document belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_documents",
                to="people.studentprofile",
                verbose_name="Student",
            ),
        ),
        migrations.AddIndex(
            model_name="documentrequestcomment",
            index=models.Index(
                fields=["document_request", "created_at"],
                name="academic_re_documen_6f5b83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentrequestcomment",
            index=models.Index(fields=["is_internal"], name="academic_re_is_inte_16daf0_idx"),
        ),
        migrations.AddIndex(
            model_name="documentrequest",
            index=models.Index(
                fields=["student", "request_status"],
                name="academic_re_student_6bbfca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentrequest",
            index=models.Index(
                fields=["document_type", "request_status"],
                name="academic_re_documen_c13cd1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentrequest",
            index=models.Index(
                fields=["request_status", "requested_date"],
                name="academic_re_request_1bfc93_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentrequest",
            index=models.Index(fields=["request_id"], name="academic_re_request_0bb3bd_idx"),
        ),
        migrations.AddIndex(
            model_name="documentrequest",
            index=models.Index(fields=["due_date"], name="academic_re_due_dat_bdea0a_idx"),
        ),
        migrations.AddIndex(
            model_name="documentusagetracker",
            index=models.Index(
                fields=["student", "document_type"],
                name="academic_re_student_efd37d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentusagetracker",
            index=models.Index(fields=["total_requested"], name="academic_re_total_r_37ffb4_idx"),
        ),
        migrations.AddIndex(
            model_name="documentusagetracker",
            index=models.Index(fields=["last_request_date"], name="academic_re_last_re_a23a65_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documentusagetracker",
            unique_together={("student", "document_type")},
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(
                fields=["student", "document_request"],
                name="academic_re_student_e87c2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(fields=["verification_code"], name="academic_re_verific_d6becd_idx"),
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(fields=["document_id"], name="academic_re_documen_46c713_idx"),
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(fields=["generated_date"], name="academic_re_generat_6c0f0a_idx"),
        ),
    ]
