# Generated by Django 5.2.4 on 2025-08-03 01:32

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_records", "0005_add_document_quota_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="documentquota",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="documentquotausage",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="documentquota",
            new_name="academic_re_student_b6eb10_idx",
            old_name="academic_re_student_0f5c4d_idx",
        ),
        migrations.RenameIndex(
            model_name="documentquota",
            new_name="academic_re_expires_2be495_idx",
            old_name="academic_re_expires_89e3f6_idx",
        ),
        migrations.RenameIndex(
            model_name="documentquota",
            new_name="academic_re_cycle_s_28f989_idx",
            old_name="academic_re_cycle_s_7b5d23_idx",
        ),
        migrations.RenameIndex(
            model_name="documentquotausage",
            new_name="academic_re_quota_i_696dff_idx",
            old_name="academic_re_quota_i_a2c4e1_idx",
        ),
        migrations.RenameIndex(
            model_name="documentquotausage",
            new_name="academic_re_documen_6ea0d7_idx",
            old_name="academic_re_documen_8f3b2a_idx",
        ),
        migrations.AddField(
            model_name="documentquota",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AddField(
            model_name="documentquota",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Indicates if this record has been soft deleted", verbose_name="Is deleted"
            ),
        ),
        migrations.AddField(
            model_name="documentquotausage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="documentquotausage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AddField(
            model_name="documentquotausage",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Indicates if this record has been soft deleted", verbose_name="Is deleted"
            ),
        ),
        migrations.AddField(
            model_name="documentquotausage",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
    ]
