# Generated by Django 5.2.4 on 2025-07-15 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherleaverequest",
            name="affected_class_parts",
            field=models.ManyToManyField(
                help_text="Class parts that need substitute coverage",
                related_name="teacher_leave_requests",
                to="scheduling.classpart",
                verbose_name="Affected Class Parts",
            ),
        ),
        migrations.AddField(
            model_name="teacherleaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_leave_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AddField(
            model_name="teacherleaverequest",
            name="substitute_assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who assigned the substitute",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_substitute_leaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Substitute Assigned By",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teacher_profile",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="teacherleaverequest",
            name="substitute_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher assigned to cover the classes",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substitute_assignments",
                to="people.teacherprofile",
                verbose_name="Substitute Teacher",
            ),
        ),
        migrations.AddField(
            model_name="teacherleaverequest",
            name="teacher",
            field=models.ForeignKey(
                help_text="Teacher requesting leave",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leave_requests",
                to="people.teacherprofile",
                verbose_name="Teacher",
            ),
        ),
        migrations.AddConstraint(
            model_name="emergencycontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("person", "is_primary"),
                name="unique_primary_contact",
            ),
        ),
        migrations.AddIndex(
            model_name="personeventlog",
            index=models.Index(fields=["person", "-timestamp"], name="people_pers_person__07f512_idx"),
        ),
        migrations.AddIndex(
            model_name="personeventlog",
            index=models.Index(fields=["action", "-timestamp"], name="people_pers_action_993c1a_idx"),
        ),
        migrations.AddConstraint(
            model_name="phonenumber",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_preferred", True)),
                fields=("person", "is_preferred"),
                name="unique_preferred_number",
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["student_id"], name="people_stud_student_550ac7_idx"),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["current_status"], name="people_stud_current_ebb8a7_idx"),
        ),
        migrations.AddIndex(
            model_name="studentauditlog",
            index=models.Index(fields=["student", "-timestamp"], name="people_stud_student_8c4852_idx"),
        ),
        migrations.AddIndex(
            model_name="studentauditlog",
            index=models.Index(fields=["action", "-timestamp"], name="people_stud_action_213120_idx"),
        ),
        migrations.AddIndex(
            model_name="studentauditlog",
            index=models.Index(
                fields=["content_type", "object_id", "-timestamp"],
                name="people_stud_content_81e2c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherleaverequest",
            index=models.Index(fields=["teacher", "leave_date"], name="people_teac_teacher_0b5adf_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherleaverequest",
            index=models.Index(
                fields=["leave_date", "approval_status"],
                name="people_teac_leave_d_50ad12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherleaverequest",
            index=models.Index(
                fields=["substitute_teacher", "leave_date"],
                name="people_teac_substit_b68bfe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherleaverequest",
            index=models.Index(
                fields=["is_emergency", "approval_status"],
                name="people_teac_is_emer_3590a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherleaverequest",
            index=models.Index(
                fields=["substitute_found", "leave_date"],
                name="people_teac_substit_97ced8_idx",
            ),
        ),
    ]
