# Generated by Django 5.2.4 on 2025-07-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("MERGE", "Merge"),
                    ("STATUS", "Status Change"),
                    ("MONK_STATUS", "Monk Status Change"),
                    ("ENROLLMENT", "Enrollment Change"),
                    ("GRADUATION", "Graduation Recorded"),
                    ("ACADEMIC", "Academic Progression"),
                    ("OTHER", "Other Change"),
                ],
                max_length=15,
                verbose_name="Action",
            ),
        ),
    ]
