# Generated by Django 5.2.4 on 2025-07-19 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_add_user_person_link"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="person",
            name="people_person_user_idx",
        ),
        migrations.RemoveField(
            model_name="person",
            name="user",
        ),
    ]
