# Generated by Django

from django.db import migrations

import apps.common.models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0006_add_student_photo"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="studentphoto",
            managers=[
                ("objects", apps.common.models.SoftDeleteManager()),
            ],
        ),
    ]
