# Generated by Django 5.2.4 on 2025-07-23 10:45

import django.db.models.manager
from django.db import migrations, models

import apps.people.models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0007_studentphoto_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="studentphoto",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="studentphoto",
            new_name="people_stud_person__2d702c_idx",
            old_name="people_stud_person__f35c19_idx",
        ),
        migrations.RenameIndex(
            model_name="studentphoto",
            new_name="people_stud_is_curr_67ef11_idx",
            old_name="people_stud_is_curr_a9e7c8_idx",
        ),
        migrations.RenameIndex(
            model_name="studentphoto",
            new_name="people_stud_upload__2e4035_idx",
            old_name="people_stud_upload__8e7e5d_idx",
        ),
        migrations.RenameIndex(
            model_name="studentphoto",
            new_name="people_stud_reminde_2391e1_idx",
            old_name="people_stud_reminde_7b9c2a_idx",
        ),
        migrations.RenameIndex(
            model_name="studentphoto",
            new_name="people_stud_file_ha_0c9bd2_idx",
            old_name="people_stud_file_ha_8f1d5f_idx",
        ),
        migrations.AlterField(
            model_name="studentphoto",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the record was created",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="studentphoto",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was marked as deleted",
                null=True,
                verbose_name="Deleted at",
            ),
        ),
        migrations.AlterField(
            model_name="studentphoto",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this record has been soft deleted",
                verbose_name="Is deleted",
            ),
        ),
        migrations.AlterField(
            model_name="studentphoto",
            name="photo_file",
            field=models.ImageField(
                help_text="Student photo file (JPEG/PNG, max 5MB)",
                upload_to=apps.people.models.student_photo_path,
                verbose_name="Photo File",
            ),
        ),
        migrations.AlterField(
            model_name="studentphoto",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Auto-generated 80x90 thumbnail",
                null=True,
                upload_to=apps.people.models.student_thumbnail_path,
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="studentphoto",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the record was last updated",
                verbose_name="Updated at",
            ),
        ),
    ]
