# Generated by Django 5.2.5 on 2025-08-20 23:47

from django.db import migrations, models

import apps.common.utils.uuid_utils


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0010_update_gender_choices_to_male_female_monk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="alternate_gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("N", "Non-Binary/Other"), ("X", "Prefer not to say")],
                default="X",
                help_text="Gender to be used on official documents",
                max_length=1,
                verbose_name="Legal Gender",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="preferred_gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("N", "Non-Binary/Other"), ("X", "Prefer not to say")],
                default="X",
                max_length=1,
                verbose_name="Preferred Gender",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="unique_id",
            field=models.UUIDField(default=apps.common.utils.uuid_utils.generate_uuid, editable=False, unique=True),
        ),
    ]
