# Generated by Django 5.2.5 on 2025-08-28 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_records', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquota',
            name='admin_fee_line_item',
            field=models.ForeignKey(blank=True, help_text='Administrative fee invoice line item that included this quota', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_quotas', to='finance.invoicelineitem', verbose_name='Administrative Fee Line Item'),
        ),
        migrations.AddField(
            model_name='documentquota',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
