# Generated by Django 5.2.5 on 2025-08-28 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_initial'),
        ('enrollment', '0002_initial'),
        ('language', '0001_initial'),
        ('people', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='languagelevelskiprequest',
            name='new_enrollment',
            field=models.ForeignKey(blank=True, help_text='Enrollment created as result of level skip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_skip_enrollments', to='enrollment.classheaderenrollment', verbose_name='New Enrollment'),
        ),
        migrations.AddField(
            model_name='languagelevelskiprequest',
            name='requested_by',
            field=models.ForeignKey(help_text='Staff member who submitted the request', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_level_skip_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='languagelevelskiprequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Manager who reviewed the request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_level_skip_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='languagelevelskiprequest',
            name='student',
            field=models.ForeignKey(help_text='Student requesting level skip', on_delete=django.db.models.deletion.PROTECT, related_name='level_skip_requests', to='people.studentprofile', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='languageprogrampromotion',
            name='initiated_by',
            field=models.ForeignKey(help_text='Staff member who initiated the promotion', on_delete=django.db.models.deletion.PROTECT, related_name='language_promotions_initiated', to=settings.AUTH_USER_MODEL, verbose_name='Initiated By'),
        ),
        migrations.AddField(
            model_name='languageprogrampromotion',
            name='source_term',
            field=models.ForeignKey(help_text='Term from which students are being promoted', on_delete=django.db.models.deletion.PROTECT, related_name='language_promotions_from', to='curriculum.term', verbose_name='Source Term'),
        ),
        migrations.AddField(
            model_name='languageprogrampromotion',
            name='target_term',
            field=models.ForeignKey(help_text='Term to which students are being promoted', on_delete=django.db.models.deletion.PROTECT, related_name='language_promotions_to', to='curriculum.term', verbose_name='Target Term'),
        ),
        migrations.AddField(
            model_name='languagestudentpromotion',
            name='promotion_batch',
            field=models.ForeignKey(help_text='Bulk promotion batch this student is part of', on_delete=django.db.models.deletion.CASCADE, related_name='student_promotions', to='language.languageprogrampromotion', verbose_name='Promotion Batch'),
        ),
        migrations.AddField(
            model_name='languagestudentpromotion',
            name='skip_approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved the level skip', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_level_skips', to=settings.AUTH_USER_MODEL, verbose_name='Skip Approved By'),
        ),
        migrations.AddField(
            model_name='languagestudentpromotion',
            name='source_class',
            field=models.ForeignKey(help_text='Class the student was enrolled in', on_delete=django.db.models.deletion.PROTECT, related_name='language_promotions_from', to='scheduling.classheader', verbose_name='Source Class'),
        ),
        migrations.AddField(
            model_name='languagestudentpromotion',
            name='student',
            field=models.ForeignKey(help_text='Student being promoted', on_delete=django.db.models.deletion.PROTECT, related_name='language_promotions', to='people.studentprofile', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='languagestudentpromotion',
            name='target_class',
            field=models.ForeignKey(blank=True, help_text='Class the student was promoted to (if successful)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='language_promotions_to', to='scheduling.classheader', verbose_name='Target Class'),
        ),
        migrations.AddIndex(
            model_name='languagelevelskiprequest',
            index=models.Index(fields=['student', 'status'], name='language_la_student_9509cc_idx'),
        ),
        migrations.AddIndex(
            model_name='languagelevelskiprequest',
            index=models.Index(fields=['program', 'status'], name='language_la_program_2b3dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='languagelevelskiprequest',
            index=models.Index(fields=['status', 'created_at'], name='language_la_status_2cddd2_idx'),
        ),
        migrations.AddIndex(
            model_name='languagelevelskiprequest',
            index=models.Index(fields=['reviewed_by', 'reviewed_at'], name='language_la_reviewe_bb1d42_idx'),
        ),
        migrations.AddIndex(
            model_name='languageprogrampromotion',
            index=models.Index(fields=['program', 'status'], name='language_la_program_78163a_idx'),
        ),
        migrations.AddIndex(
            model_name='languageprogrampromotion',
            index=models.Index(fields=['source_term', 'target_term'], name='language_la_source__563d55_idx'),
        ),
        migrations.AddIndex(
            model_name='languageprogrampromotion',
            index=models.Index(fields=['initiated_at'], name='language_la_initiat_6708d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='languageprogrampromotion',
            unique_together={('source_term', 'target_term', 'program')},
        ),
        migrations.AddIndex(
            model_name='languagestudentpromotion',
            index=models.Index(fields=['promotion_batch', 'result'], name='language_la_promoti_907118_idx'),
        ),
        migrations.AddIndex(
            model_name='languagestudentpromotion',
            index=models.Index(fields=['student'], name='language_la_student_1434ea_idx'),
        ),
        migrations.AddIndex(
            model_name='languagestudentpromotion',
            index=models.Index(fields=['from_level', 'to_level'], name='language_la_from_le_8fe0ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='languagestudentpromotion',
            unique_together={('promotion_batch', 'student')},
        ),
    ]
